// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stock.proto

package grpc;

public final class StockServiceOuterClass {
  private StockServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VentaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VentaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idProducto = 1;</code>
     */
    java.lang.String getIdProducto();
    /**
     * <code>string idProducto = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdProductoBytes();

    /**
     * <code>int32 cantidad = 2;</code>
     */
    int getCantidad();
  }
  /**
   * Protobuf type {@code VentaRequest}
   */
  public  static final class VentaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VentaRequest)
      VentaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VentaRequest.newBuilder() to construct.
    private VentaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VentaRequest() {
      idProducto_ = "";
      cantidad_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VentaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idProducto_ = s;
              break;
            }
            case 16: {

              cantidad_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.StockServiceOuterClass.internal_static_VentaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.StockServiceOuterClass.internal_static_VentaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.StockServiceOuterClass.VentaRequest.class, grpc.StockServiceOuterClass.VentaRequest.Builder.class);
    }

    public static final int IDPRODUCTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idProducto_;
    /**
     * <code>string idProducto = 1;</code>
     */
    public java.lang.String getIdProducto() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idProducto_ = s;
        return s;
      }
    }
    /**
     * <code>string idProducto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdProductoBytes() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idProducto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANTIDAD_FIELD_NUMBER = 2;
    private int cantidad_;
    /**
     * <code>int32 cantidad = 2;</code>
     */
    public int getCantidad() {
      return cantidad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdProductoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idProducto_);
      }
      if (cantidad_ != 0) {
        output.writeInt32(2, cantidad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdProductoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idProducto_);
      }
      if (cantidad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cantidad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.StockServiceOuterClass.VentaRequest)) {
        return super.equals(obj);
      }
      grpc.StockServiceOuterClass.VentaRequest other = (grpc.StockServiceOuterClass.VentaRequest) obj;

      boolean result = true;
      result = result && getIdProducto()
          .equals(other.getIdProducto());
      result = result && (getCantidad()
          == other.getCantidad());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPRODUCTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdProducto().hashCode();
      hash = (37 * hash) + CANTIDAD_FIELD_NUMBER;
      hash = (53 * hash) + getCantidad();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.VentaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.StockServiceOuterClass.VentaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VentaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VentaRequest)
        grpc.StockServiceOuterClass.VentaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.StockServiceOuterClass.internal_static_VentaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.StockServiceOuterClass.internal_static_VentaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.StockServiceOuterClass.VentaRequest.class, grpc.StockServiceOuterClass.VentaRequest.Builder.class);
      }

      // Construct using grpc.StockServiceOuterClass.VentaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idProducto_ = "";

        cantidad_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.StockServiceOuterClass.internal_static_VentaRequest_descriptor;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.VentaRequest getDefaultInstanceForType() {
        return grpc.StockServiceOuterClass.VentaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.VentaRequest build() {
        grpc.StockServiceOuterClass.VentaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.VentaRequest buildPartial() {
        grpc.StockServiceOuterClass.VentaRequest result = new grpc.StockServiceOuterClass.VentaRequest(this);
        result.idProducto_ = idProducto_;
        result.cantidad_ = cantidad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.StockServiceOuterClass.VentaRequest) {
          return mergeFrom((grpc.StockServiceOuterClass.VentaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.StockServiceOuterClass.VentaRequest other) {
        if (other == grpc.StockServiceOuterClass.VentaRequest.getDefaultInstance()) return this;
        if (!other.getIdProducto().isEmpty()) {
          idProducto_ = other.idProducto_;
          onChanged();
        }
        if (other.getCantidad() != 0) {
          setCantidad(other.getCantidad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.StockServiceOuterClass.VentaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.StockServiceOuterClass.VentaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idProducto_ = "";
      /**
       * <code>string idProducto = 1;</code>
       */
      public java.lang.String getIdProducto() {
        java.lang.Object ref = idProducto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idProducto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdProductoBytes() {
        java.lang.Object ref = idProducto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idProducto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProducto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idProducto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder clearIdProducto() {
        
        idProducto_ = getDefaultInstance().getIdProducto();
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProductoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idProducto_ = value;
        onChanged();
        return this;
      }

      private int cantidad_ ;
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public int getCantidad() {
        return cantidad_;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder setCantidad(int value) {
        
        cantidad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder clearCantidad() {
        
        cantidad_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VentaRequest)
    }

    // @@protoc_insertion_point(class_scope:VentaRequest)
    private static final grpc.StockServiceOuterClass.VentaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.StockServiceOuterClass.VentaRequest();
    }

    public static grpc.StockServiceOuterClass.VentaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VentaRequest>
        PARSER = new com.google.protobuf.AbstractParser<VentaRequest>() {
      @java.lang.Override
      public VentaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VentaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VentaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VentaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.StockServiceOuterClass.VentaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RestoProductoReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RestoProductoReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * cantidad que queda de producto
     * </pre>
     *
     * <code>int32 resto = 1;</code>
     */
    int getResto();
  }
  /**
   * Protobuf type {@code RestoProductoReply}
   */
  public  static final class RestoProductoReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RestoProductoReply)
      RestoProductoReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RestoProductoReply.newBuilder() to construct.
    private RestoProductoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RestoProductoReply() {
      resto_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RestoProductoReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              resto_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.StockServiceOuterClass.internal_static_RestoProductoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.StockServiceOuterClass.internal_static_RestoProductoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.StockServiceOuterClass.RestoProductoReply.class, grpc.StockServiceOuterClass.RestoProductoReply.Builder.class);
    }

    public static final int RESTO_FIELD_NUMBER = 1;
    private int resto_;
    /**
     * <pre>
     * cantidad que queda de producto
     * </pre>
     *
     * <code>int32 resto = 1;</code>
     */
    public int getResto() {
      return resto_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resto_ != 0) {
        output.writeInt32(1, resto_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resto_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.StockServiceOuterClass.RestoProductoReply)) {
        return super.equals(obj);
      }
      grpc.StockServiceOuterClass.RestoProductoReply other = (grpc.StockServiceOuterClass.RestoProductoReply) obj;

      boolean result = true;
      result = result && (getResto()
          == other.getResto());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESTO_FIELD_NUMBER;
      hash = (53 * hash) + getResto();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.RestoProductoReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.StockServiceOuterClass.RestoProductoReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RestoProductoReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RestoProductoReply)
        grpc.StockServiceOuterClass.RestoProductoReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.StockServiceOuterClass.internal_static_RestoProductoReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.StockServiceOuterClass.internal_static_RestoProductoReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.StockServiceOuterClass.RestoProductoReply.class, grpc.StockServiceOuterClass.RestoProductoReply.Builder.class);
      }

      // Construct using grpc.StockServiceOuterClass.RestoProductoReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resto_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.StockServiceOuterClass.internal_static_RestoProductoReply_descriptor;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.RestoProductoReply getDefaultInstanceForType() {
        return grpc.StockServiceOuterClass.RestoProductoReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.RestoProductoReply build() {
        grpc.StockServiceOuterClass.RestoProductoReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.RestoProductoReply buildPartial() {
        grpc.StockServiceOuterClass.RestoProductoReply result = new grpc.StockServiceOuterClass.RestoProductoReply(this);
        result.resto_ = resto_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.StockServiceOuterClass.RestoProductoReply) {
          return mergeFrom((grpc.StockServiceOuterClass.RestoProductoReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.StockServiceOuterClass.RestoProductoReply other) {
        if (other == grpc.StockServiceOuterClass.RestoProductoReply.getDefaultInstance()) return this;
        if (other.getResto() != 0) {
          setResto(other.getResto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.StockServiceOuterClass.RestoProductoReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.StockServiceOuterClass.RestoProductoReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resto_ ;
      /**
       * <pre>
       * cantidad que queda de producto
       * </pre>
       *
       * <code>int32 resto = 1;</code>
       */
      public int getResto() {
        return resto_;
      }
      /**
       * <pre>
       * cantidad que queda de producto
       * </pre>
       *
       * <code>int32 resto = 1;</code>
       */
      public Builder setResto(int value) {
        
        resto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cantidad que queda de producto
       * </pre>
       *
       * <code>int32 resto = 1;</code>
       */
      public Builder clearResto() {
        
        resto_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RestoProductoReply)
    }

    // @@protoc_insertion_point(class_scope:RestoProductoReply)
    private static final grpc.StockServiceOuterClass.RestoProductoReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.StockServiceOuterClass.RestoProductoReply();
    }

    public static grpc.StockServiceOuterClass.RestoProductoReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RestoProductoReply>
        PARSER = new com.google.protobuf.AbstractParser<RestoProductoReply>() {
      @java.lang.Override
      public RestoProductoReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestoProductoReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RestoProductoReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RestoProductoReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.StockServiceOuterClass.RestoProductoReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StockRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StockRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * quiero preguntar cuántos productos están por debajo de este umbral
     * </pre>
     *
     * <code>int32 umbral = 1;</code>
     */
    int getUmbral();
  }
  /**
   * Protobuf type {@code StockRequest}
   */
  public  static final class StockRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StockRequest)
      StockRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StockRequest.newBuilder() to construct.
    private StockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockRequest() {
      umbral_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StockRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              umbral_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.StockServiceOuterClass.internal_static_StockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.StockServiceOuterClass.internal_static_StockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.StockServiceOuterClass.StockRequest.class, grpc.StockServiceOuterClass.StockRequest.Builder.class);
    }

    public static final int UMBRAL_FIELD_NUMBER = 1;
    private int umbral_;
    /**
     * <pre>
     * quiero preguntar cuántos productos están por debajo de este umbral
     * </pre>
     *
     * <code>int32 umbral = 1;</code>
     */
    public int getUmbral() {
      return umbral_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (umbral_ != 0) {
        output.writeInt32(1, umbral_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (umbral_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, umbral_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.StockServiceOuterClass.StockRequest)) {
        return super.equals(obj);
      }
      grpc.StockServiceOuterClass.StockRequest other = (grpc.StockServiceOuterClass.StockRequest) obj;

      boolean result = true;
      result = result && (getUmbral()
          == other.getUmbral());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UMBRAL_FIELD_NUMBER;
      hash = (53 * hash) + getUmbral();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.StockRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.StockServiceOuterClass.StockRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StockRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StockRequest)
        grpc.StockServiceOuterClass.StockRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.StockServiceOuterClass.internal_static_StockRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.StockServiceOuterClass.internal_static_StockRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.StockServiceOuterClass.StockRequest.class, grpc.StockServiceOuterClass.StockRequest.Builder.class);
      }

      // Construct using grpc.StockServiceOuterClass.StockRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        umbral_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.StockServiceOuterClass.internal_static_StockRequest_descriptor;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.StockRequest getDefaultInstanceForType() {
        return grpc.StockServiceOuterClass.StockRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.StockRequest build() {
        grpc.StockServiceOuterClass.StockRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.StockRequest buildPartial() {
        grpc.StockServiceOuterClass.StockRequest result = new grpc.StockServiceOuterClass.StockRequest(this);
        result.umbral_ = umbral_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.StockServiceOuterClass.StockRequest) {
          return mergeFrom((grpc.StockServiceOuterClass.StockRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.StockServiceOuterClass.StockRequest other) {
        if (other == grpc.StockServiceOuterClass.StockRequest.getDefaultInstance()) return this;
        if (other.getUmbral() != 0) {
          setUmbral(other.getUmbral());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.StockServiceOuterClass.StockRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.StockServiceOuterClass.StockRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int umbral_ ;
      /**
       * <pre>
       * quiero preguntar cuántos productos están por debajo de este umbral
       * </pre>
       *
       * <code>int32 umbral = 1;</code>
       */
      public int getUmbral() {
        return umbral_;
      }
      /**
       * <pre>
       * quiero preguntar cuántos productos están por debajo de este umbral
       * </pre>
       *
       * <code>int32 umbral = 1;</code>
       */
      public Builder setUmbral(int value) {
        
        umbral_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * quiero preguntar cuántos productos están por debajo de este umbral
       * </pre>
       *
       * <code>int32 umbral = 1;</code>
       */
      public Builder clearUmbral() {
        
        umbral_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StockRequest)
    }

    // @@protoc_insertion_point(class_scope:StockRequest)
    private static final grpc.StockServiceOuterClass.StockRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.StockServiceOuterClass.StockRequest();
    }

    public static grpc.StockServiceOuterClass.StockRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockRequest>
        PARSER = new com.google.protobuf.AbstractParser<StockRequest>() {
      @java.lang.Override
      public StockRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.StockServiceOuterClass.StockRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductosReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductosReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idProducto = 1;</code>
     */
    java.lang.String getIdProducto();
    /**
     * <code>string idProducto = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdProductoBytes();
  }
  /**
   * Protobuf type {@code ProductosReply}
   */
  public  static final class ProductosReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductosReply)
      ProductosReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductosReply.newBuilder() to construct.
    private ProductosReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductosReply() {
      idProducto_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductosReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idProducto_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.StockServiceOuterClass.internal_static_ProductosReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.StockServiceOuterClass.internal_static_ProductosReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.StockServiceOuterClass.ProductosReply.class, grpc.StockServiceOuterClass.ProductosReply.Builder.class);
    }

    public static final int IDPRODUCTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idProducto_;
    /**
     * <code>string idProducto = 1;</code>
     */
    public java.lang.String getIdProducto() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idProducto_ = s;
        return s;
      }
    }
    /**
     * <code>string idProducto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdProductoBytes() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idProducto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdProductoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idProducto_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdProductoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idProducto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.StockServiceOuterClass.ProductosReply)) {
        return super.equals(obj);
      }
      grpc.StockServiceOuterClass.ProductosReply other = (grpc.StockServiceOuterClass.ProductosReply) obj;

      boolean result = true;
      result = result && getIdProducto()
          .equals(other.getIdProducto());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPRODUCTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdProducto().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.ProductosReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.StockServiceOuterClass.ProductosReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductosReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductosReply)
        grpc.StockServiceOuterClass.ProductosReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.StockServiceOuterClass.internal_static_ProductosReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.StockServiceOuterClass.internal_static_ProductosReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.StockServiceOuterClass.ProductosReply.class, grpc.StockServiceOuterClass.ProductosReply.Builder.class);
      }

      // Construct using grpc.StockServiceOuterClass.ProductosReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idProducto_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.StockServiceOuterClass.internal_static_ProductosReply_descriptor;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.ProductosReply getDefaultInstanceForType() {
        return grpc.StockServiceOuterClass.ProductosReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.ProductosReply build() {
        grpc.StockServiceOuterClass.ProductosReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.ProductosReply buildPartial() {
        grpc.StockServiceOuterClass.ProductosReply result = new grpc.StockServiceOuterClass.ProductosReply(this);
        result.idProducto_ = idProducto_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.StockServiceOuterClass.ProductosReply) {
          return mergeFrom((grpc.StockServiceOuterClass.ProductosReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.StockServiceOuterClass.ProductosReply other) {
        if (other == grpc.StockServiceOuterClass.ProductosReply.getDefaultInstance()) return this;
        if (!other.getIdProducto().isEmpty()) {
          idProducto_ = other.idProducto_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.StockServiceOuterClass.ProductosReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.StockServiceOuterClass.ProductosReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idProducto_ = "";
      /**
       * <code>string idProducto = 1;</code>
       */
      public java.lang.String getIdProducto() {
        java.lang.Object ref = idProducto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idProducto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdProductoBytes() {
        java.lang.Object ref = idProducto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idProducto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProducto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idProducto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder clearIdProducto() {
        
        idProducto_ = getDefaultInstance().getIdProducto();
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProductoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idProducto_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductosReply)
    }

    // @@protoc_insertion_point(class_scope:ProductosReply)
    private static final grpc.StockServiceOuterClass.ProductosReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.StockServiceOuterClass.ProductosReply();
    }

    public static grpc.StockServiceOuterClass.ProductosReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductosReply>
        PARSER = new com.google.protobuf.AbstractParser<ProductosReply>() {
      @java.lang.Override
      public ProductosReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductosReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductosReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductosReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.StockServiceOuterClass.ProductosReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DameStockRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DameStockRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idProducto = 1;</code>
     */
    java.lang.String getIdProducto();
    /**
     * <code>string idProducto = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdProductoBytes();
  }
  /**
   * Protobuf type {@code DameStockRequest}
   */
  public  static final class DameStockRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DameStockRequest)
      DameStockRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DameStockRequest.newBuilder() to construct.
    private DameStockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DameStockRequest() {
      idProducto_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DameStockRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idProducto_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.StockServiceOuterClass.internal_static_DameStockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.StockServiceOuterClass.internal_static_DameStockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.StockServiceOuterClass.DameStockRequest.class, grpc.StockServiceOuterClass.DameStockRequest.Builder.class);
    }

    public static final int IDPRODUCTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idProducto_;
    /**
     * <code>string idProducto = 1;</code>
     */
    public java.lang.String getIdProducto() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idProducto_ = s;
        return s;
      }
    }
    /**
     * <code>string idProducto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdProductoBytes() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idProducto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdProductoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idProducto_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdProductoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idProducto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.StockServiceOuterClass.DameStockRequest)) {
        return super.equals(obj);
      }
      grpc.StockServiceOuterClass.DameStockRequest other = (grpc.StockServiceOuterClass.DameStockRequest) obj;

      boolean result = true;
      result = result && getIdProducto()
          .equals(other.getIdProducto());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPRODUCTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdProducto().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.StockServiceOuterClass.DameStockRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.StockServiceOuterClass.DameStockRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DameStockRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DameStockRequest)
        grpc.StockServiceOuterClass.DameStockRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.StockServiceOuterClass.internal_static_DameStockRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.StockServiceOuterClass.internal_static_DameStockRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.StockServiceOuterClass.DameStockRequest.class, grpc.StockServiceOuterClass.DameStockRequest.Builder.class);
      }

      // Construct using grpc.StockServiceOuterClass.DameStockRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idProducto_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.StockServiceOuterClass.internal_static_DameStockRequest_descriptor;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.DameStockRequest getDefaultInstanceForType() {
        return grpc.StockServiceOuterClass.DameStockRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.DameStockRequest build() {
        grpc.StockServiceOuterClass.DameStockRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.StockServiceOuterClass.DameStockRequest buildPartial() {
        grpc.StockServiceOuterClass.DameStockRequest result = new grpc.StockServiceOuterClass.DameStockRequest(this);
        result.idProducto_ = idProducto_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.StockServiceOuterClass.DameStockRequest) {
          return mergeFrom((grpc.StockServiceOuterClass.DameStockRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.StockServiceOuterClass.DameStockRequest other) {
        if (other == grpc.StockServiceOuterClass.DameStockRequest.getDefaultInstance()) return this;
        if (!other.getIdProducto().isEmpty()) {
          idProducto_ = other.idProducto_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.StockServiceOuterClass.DameStockRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.StockServiceOuterClass.DameStockRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idProducto_ = "";
      /**
       * <code>string idProducto = 1;</code>
       */
      public java.lang.String getIdProducto() {
        java.lang.Object ref = idProducto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idProducto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdProductoBytes() {
        java.lang.Object ref = idProducto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idProducto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProducto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idProducto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder clearIdProducto() {
        
        idProducto_ = getDefaultInstance().getIdProducto();
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProductoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idProducto_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DameStockRequest)
    }

    // @@protoc_insertion_point(class_scope:DameStockRequest)
    private static final grpc.StockServiceOuterClass.DameStockRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.StockServiceOuterClass.DameStockRequest();
    }

    public static grpc.StockServiceOuterClass.DameStockRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DameStockRequest>
        PARSER = new com.google.protobuf.AbstractParser<DameStockRequest>() {
      @java.lang.Override
      public DameStockRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DameStockRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DameStockRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DameStockRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.StockServiceOuterClass.DameStockRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VentaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VentaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RestoProductoReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RestoProductoReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductosReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductosReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DameStockRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DameStockRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Stock.proto\"4\n\014VentaRequest\022\022\n\nidProdu" +
      "cto\030\001 \001(\t\022\020\n\010cantidad\030\002 \001(\005\"#\n\022RestoProd" +
      "uctoReply\022\r\n\005resto\030\001 \001(\005\"\036\n\014StockRequest" +
      "\022\016\n\006umbral\030\001 \001(\005\"$\n\016ProductosReply\022\022\n\nid" +
      "Producto\030\001 \001(\t\"&\n\020DameStockRequest\022\022\n\nid" +
      "Producto\030\001 \001(\t2\254\001\n\014StockService\0226\n\016regis" +
      "trarVenta\022\r.VentaRequest\032\023.RestoProducto" +
      "Reply\"\000\022/\n\tbajoStock\022\r.StockRequest\032\017.Pr" +
      "oductosReply\"\0000\001\0223\n\tdameStock\022\021.DameStoc" +
      "kRequest\032\r.VentaRequest\"\000(\0010\001B\036\n\004grpcB\026S" +
      "tockServiceOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VentaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VentaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VentaRequest_descriptor,
        new java.lang.String[] { "IdProducto", "Cantidad", });
    internal_static_RestoProductoReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RestoProductoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RestoProductoReply_descriptor,
        new java.lang.String[] { "Resto", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "Umbral", });
    internal_static_ProductosReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProductosReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductosReply_descriptor,
        new java.lang.String[] { "IdProducto", });
    internal_static_DameStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DameStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DameStockRequest_descriptor,
        new java.lang.String[] { "IdProducto", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
