// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sesion10.proto

package grpc;

public final class TramitadorOuterClass {
  private TramitadorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PedidoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PedidoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idPedido = 1;</code>
     */
    java.lang.String getIdPedido();
    /**
     * <code>string idPedido = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdPedidoBytes();

    /**
     * <pre>
     * Dirección del cliente
     * </pre>
     *
     * <code>string direccion = 2;</code>
     */
    java.lang.String getDireccion();
    /**
     * <pre>
     * Dirección del cliente
     * </pre>
     *
     * <code>string direccion = 2;</code>
     */
    com.google.protobuf.ByteString
        getDireccionBytes();

    /**
     * <pre>
     * Restaurante del pedido
     * </pre>
     *
     * <code>int32 restaurante = 3;</code>
     */
    int getRestaurante();

    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    java.util.List<grpc.TramitadorOuterClass.ProductoRequest> 
        getProductosList();
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    grpc.TramitadorOuterClass.ProductoRequest getProductos(int index);
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    int getProductosCount();
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    java.util.List<? extends grpc.TramitadorOuterClass.ProductoRequestOrBuilder> 
        getProductosOrBuilderList();
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    grpc.TramitadorOuterClass.ProductoRequestOrBuilder getProductosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PedidoRequest}
   */
  public  static final class PedidoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PedidoRequest)
      PedidoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PedidoRequest.newBuilder() to construct.
    private PedidoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PedidoRequest() {
      idPedido_ = "";
      direccion_ = "";
      restaurante_ = 0;
      productos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PedidoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idPedido_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              direccion_ = s;
              break;
            }
            case 24: {

              restaurante_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                productos_ = new java.util.ArrayList<grpc.TramitadorOuterClass.ProductoRequest>();
                mutable_bitField0_ |= 0x00000008;
              }
              productos_.add(
                  input.readMessage(grpc.TramitadorOuterClass.ProductoRequest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          productos_ = java.util.Collections.unmodifiableList(productos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.TramitadorOuterClass.internal_static_PedidoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.TramitadorOuterClass.internal_static_PedidoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.TramitadorOuterClass.PedidoRequest.class, grpc.TramitadorOuterClass.PedidoRequest.Builder.class);
    }

    private int bitField0_;
    public static final int IDPEDIDO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idPedido_;
    /**
     * <code>string idPedido = 1;</code>
     */
    public java.lang.String getIdPedido() {
      java.lang.Object ref = idPedido_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idPedido_ = s;
        return s;
      }
    }
    /**
     * <code>string idPedido = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdPedidoBytes() {
      java.lang.Object ref = idPedido_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idPedido_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECCION_FIELD_NUMBER = 2;
    private volatile java.lang.Object direccion_;
    /**
     * <pre>
     * Dirección del cliente
     * </pre>
     *
     * <code>string direccion = 2;</code>
     */
    public java.lang.String getDireccion() {
      java.lang.Object ref = direccion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direccion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Dirección del cliente
     * </pre>
     *
     * <code>string direccion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDireccionBytes() {
      java.lang.Object ref = direccion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direccion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESTAURANTE_FIELD_NUMBER = 3;
    private int restaurante_;
    /**
     * <pre>
     * Restaurante del pedido
     * </pre>
     *
     * <code>int32 restaurante = 3;</code>
     */
    public int getRestaurante() {
      return restaurante_;
    }

    public static final int PRODUCTOS_FIELD_NUMBER = 4;
    private java.util.List<grpc.TramitadorOuterClass.ProductoRequest> productos_;
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    public java.util.List<grpc.TramitadorOuterClass.ProductoRequest> getProductosList() {
      return productos_;
    }
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    public java.util.List<? extends grpc.TramitadorOuterClass.ProductoRequestOrBuilder> 
        getProductosOrBuilderList() {
      return productos_;
    }
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    public int getProductosCount() {
      return productos_.size();
    }
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    public grpc.TramitadorOuterClass.ProductoRequest getProductos(int index) {
      return productos_.get(index);
    }
    /**
     * <code>repeated .ProductoRequest productos = 4;</code>
     */
    public grpc.TramitadorOuterClass.ProductoRequestOrBuilder getProductosOrBuilder(
        int index) {
      return productos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdPedidoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idPedido_);
      }
      if (!getDireccionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, direccion_);
      }
      if (restaurante_ != 0) {
        output.writeInt32(3, restaurante_);
      }
      for (int i = 0; i < productos_.size(); i++) {
        output.writeMessage(4, productos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdPedidoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idPedido_);
      }
      if (!getDireccionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, direccion_);
      }
      if (restaurante_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, restaurante_);
      }
      for (int i = 0; i < productos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, productos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.TramitadorOuterClass.PedidoRequest)) {
        return super.equals(obj);
      }
      grpc.TramitadorOuterClass.PedidoRequest other = (grpc.TramitadorOuterClass.PedidoRequest) obj;

      boolean result = true;
      result = result && getIdPedido()
          .equals(other.getIdPedido());
      result = result && getDireccion()
          .equals(other.getDireccion());
      result = result && (getRestaurante()
          == other.getRestaurante());
      result = result && getProductosList()
          .equals(other.getProductosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPEDIDO_FIELD_NUMBER;
      hash = (53 * hash) + getIdPedido().hashCode();
      hash = (37 * hash) + DIRECCION_FIELD_NUMBER;
      hash = (53 * hash) + getDireccion().hashCode();
      hash = (37 * hash) + RESTAURANTE_FIELD_NUMBER;
      hash = (53 * hash) + getRestaurante();
      if (getProductosCount() > 0) {
        hash = (37 * hash) + PRODUCTOS_FIELD_NUMBER;
        hash = (53 * hash) + getProductosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.TramitadorOuterClass.PedidoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PedidoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PedidoRequest)
        grpc.TramitadorOuterClass.PedidoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.TramitadorOuterClass.internal_static_PedidoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.TramitadorOuterClass.internal_static_PedidoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.TramitadorOuterClass.PedidoRequest.class, grpc.TramitadorOuterClass.PedidoRequest.Builder.class);
      }

      // Construct using grpc.TramitadorOuterClass.PedidoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idPedido_ = "";

        direccion_ = "";

        restaurante_ = 0;

        if (productosBuilder_ == null) {
          productos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          productosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.TramitadorOuterClass.internal_static_PedidoRequest_descriptor;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoRequest getDefaultInstanceForType() {
        return grpc.TramitadorOuterClass.PedidoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoRequest build() {
        grpc.TramitadorOuterClass.PedidoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoRequest buildPartial() {
        grpc.TramitadorOuterClass.PedidoRequest result = new grpc.TramitadorOuterClass.PedidoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.idPedido_ = idPedido_;
        result.direccion_ = direccion_;
        result.restaurante_ = restaurante_;
        if (productosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            productos_ = java.util.Collections.unmodifiableList(productos_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.productos_ = productos_;
        } else {
          result.productos_ = productosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.TramitadorOuterClass.PedidoRequest) {
          return mergeFrom((grpc.TramitadorOuterClass.PedidoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.TramitadorOuterClass.PedidoRequest other) {
        if (other == grpc.TramitadorOuterClass.PedidoRequest.getDefaultInstance()) return this;
        if (!other.getIdPedido().isEmpty()) {
          idPedido_ = other.idPedido_;
          onChanged();
        }
        if (!other.getDireccion().isEmpty()) {
          direccion_ = other.direccion_;
          onChanged();
        }
        if (other.getRestaurante() != 0) {
          setRestaurante(other.getRestaurante());
        }
        if (productosBuilder_ == null) {
          if (!other.productos_.isEmpty()) {
            if (productos_.isEmpty()) {
              productos_ = other.productos_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureProductosIsMutable();
              productos_.addAll(other.productos_);
            }
            onChanged();
          }
        } else {
          if (!other.productos_.isEmpty()) {
            if (productosBuilder_.isEmpty()) {
              productosBuilder_.dispose();
              productosBuilder_ = null;
              productos_ = other.productos_;
              bitField0_ = (bitField0_ & ~0x00000008);
              productosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductosFieldBuilder() : null;
            } else {
              productosBuilder_.addAllMessages(other.productos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.TramitadorOuterClass.PedidoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.TramitadorOuterClass.PedidoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object idPedido_ = "";
      /**
       * <code>string idPedido = 1;</code>
       */
      public java.lang.String getIdPedido() {
        java.lang.Object ref = idPedido_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idPedido_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idPedido = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdPedidoBytes() {
        java.lang.Object ref = idPedido_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idPedido_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idPedido = 1;</code>
       */
      public Builder setIdPedido(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idPedido_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idPedido = 1;</code>
       */
      public Builder clearIdPedido() {
        
        idPedido_ = getDefaultInstance().getIdPedido();
        onChanged();
        return this;
      }
      /**
       * <code>string idPedido = 1;</code>
       */
      public Builder setIdPedidoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idPedido_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object direccion_ = "";
      /**
       * <pre>
       * Dirección del cliente
       * </pre>
       *
       * <code>string direccion = 2;</code>
       */
      public java.lang.String getDireccion() {
        java.lang.Object ref = direccion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direccion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Dirección del cliente
       * </pre>
       *
       * <code>string direccion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDireccionBytes() {
        java.lang.Object ref = direccion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direccion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Dirección del cliente
       * </pre>
       *
       * <code>string direccion = 2;</code>
       */
      public Builder setDireccion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direccion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Dirección del cliente
       * </pre>
       *
       * <code>string direccion = 2;</code>
       */
      public Builder clearDireccion() {
        
        direccion_ = getDefaultInstance().getDireccion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Dirección del cliente
       * </pre>
       *
       * <code>string direccion = 2;</code>
       */
      public Builder setDireccionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direccion_ = value;
        onChanged();
        return this;
      }

      private int restaurante_ ;
      /**
       * <pre>
       * Restaurante del pedido
       * </pre>
       *
       * <code>int32 restaurante = 3;</code>
       */
      public int getRestaurante() {
        return restaurante_;
      }
      /**
       * <pre>
       * Restaurante del pedido
       * </pre>
       *
       * <code>int32 restaurante = 3;</code>
       */
      public Builder setRestaurante(int value) {
        
        restaurante_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Restaurante del pedido
       * </pre>
       *
       * <code>int32 restaurante = 3;</code>
       */
      public Builder clearRestaurante() {
        
        restaurante_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<grpc.TramitadorOuterClass.ProductoRequest> productos_ =
        java.util.Collections.emptyList();
      private void ensureProductosIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          productos_ = new java.util.ArrayList<grpc.TramitadorOuterClass.ProductoRequest>(productos_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.TramitadorOuterClass.ProductoRequest, grpc.TramitadorOuterClass.ProductoRequest.Builder, grpc.TramitadorOuterClass.ProductoRequestOrBuilder> productosBuilder_;

      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public java.util.List<grpc.TramitadorOuterClass.ProductoRequest> getProductosList() {
        if (productosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productos_);
        } else {
          return productosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public int getProductosCount() {
        if (productosBuilder_ == null) {
          return productos_.size();
        } else {
          return productosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public grpc.TramitadorOuterClass.ProductoRequest getProductos(int index) {
        if (productosBuilder_ == null) {
          return productos_.get(index);
        } else {
          return productosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder setProductos(
          int index, grpc.TramitadorOuterClass.ProductoRequest value) {
        if (productosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductosIsMutable();
          productos_.set(index, value);
          onChanged();
        } else {
          productosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder setProductos(
          int index, grpc.TramitadorOuterClass.ProductoRequest.Builder builderForValue) {
        if (productosBuilder_ == null) {
          ensureProductosIsMutable();
          productos_.set(index, builderForValue.build());
          onChanged();
        } else {
          productosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder addProductos(grpc.TramitadorOuterClass.ProductoRequest value) {
        if (productosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductosIsMutable();
          productos_.add(value);
          onChanged();
        } else {
          productosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder addProductos(
          int index, grpc.TramitadorOuterClass.ProductoRequest value) {
        if (productosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductosIsMutable();
          productos_.add(index, value);
          onChanged();
        } else {
          productosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder addProductos(
          grpc.TramitadorOuterClass.ProductoRequest.Builder builderForValue) {
        if (productosBuilder_ == null) {
          ensureProductosIsMutable();
          productos_.add(builderForValue.build());
          onChanged();
        } else {
          productosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder addProductos(
          int index, grpc.TramitadorOuterClass.ProductoRequest.Builder builderForValue) {
        if (productosBuilder_ == null) {
          ensureProductosIsMutable();
          productos_.add(index, builderForValue.build());
          onChanged();
        } else {
          productosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder addAllProductos(
          java.lang.Iterable<? extends grpc.TramitadorOuterClass.ProductoRequest> values) {
        if (productosBuilder_ == null) {
          ensureProductosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, productos_);
          onChanged();
        } else {
          productosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder clearProductos() {
        if (productosBuilder_ == null) {
          productos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          productosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public Builder removeProductos(int index) {
        if (productosBuilder_ == null) {
          ensureProductosIsMutable();
          productos_.remove(index);
          onChanged();
        } else {
          productosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public grpc.TramitadorOuterClass.ProductoRequest.Builder getProductosBuilder(
          int index) {
        return getProductosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public grpc.TramitadorOuterClass.ProductoRequestOrBuilder getProductosOrBuilder(
          int index) {
        if (productosBuilder_ == null) {
          return productos_.get(index);  } else {
          return productosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public java.util.List<? extends grpc.TramitadorOuterClass.ProductoRequestOrBuilder> 
           getProductosOrBuilderList() {
        if (productosBuilder_ != null) {
          return productosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productos_);
        }
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public grpc.TramitadorOuterClass.ProductoRequest.Builder addProductosBuilder() {
        return getProductosFieldBuilder().addBuilder(
            grpc.TramitadorOuterClass.ProductoRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public grpc.TramitadorOuterClass.ProductoRequest.Builder addProductosBuilder(
          int index) {
        return getProductosFieldBuilder().addBuilder(
            index, grpc.TramitadorOuterClass.ProductoRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductoRequest productos = 4;</code>
       */
      public java.util.List<grpc.TramitadorOuterClass.ProductoRequest.Builder> 
           getProductosBuilderList() {
        return getProductosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.TramitadorOuterClass.ProductoRequest, grpc.TramitadorOuterClass.ProductoRequest.Builder, grpc.TramitadorOuterClass.ProductoRequestOrBuilder> 
          getProductosFieldBuilder() {
        if (productosBuilder_ == null) {
          productosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              grpc.TramitadorOuterClass.ProductoRequest, grpc.TramitadorOuterClass.ProductoRequest.Builder, grpc.TramitadorOuterClass.ProductoRequestOrBuilder>(
                  productos_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          productos_ = null;
        }
        return productosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PedidoRequest)
    }

    // @@protoc_insertion_point(class_scope:PedidoRequest)
    private static final grpc.TramitadorOuterClass.PedidoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.TramitadorOuterClass.PedidoRequest();
    }

    public static grpc.TramitadorOuterClass.PedidoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PedidoRequest>
        PARSER = new com.google.protobuf.AbstractParser<PedidoRequest>() {
      @java.lang.Override
      public PedidoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PedidoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PedidoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PedidoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.TramitadorOuterClass.PedidoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 cantidad = 2;</code>
     */
    int getCantidad();

    /**
     * <code>double precio = 3;</code>
     */
    double getPrecio();
  }
  /**
   * Protobuf type {@code ProductoRequest}
   */
  public  static final class ProductoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductoRequest)
      ProductoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductoRequest.newBuilder() to construct.
    private ProductoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductoRequest() {
      id_ = "";
      cantidad_ = 0;
      precio_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              cantidad_ = input.readInt32();
              break;
            }
            case 25: {

              precio_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.TramitadorOuterClass.internal_static_ProductoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.TramitadorOuterClass.internal_static_ProductoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.TramitadorOuterClass.ProductoRequest.class, grpc.TramitadorOuterClass.ProductoRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANTIDAD_FIELD_NUMBER = 2;
    private int cantidad_;
    /**
     * <code>int32 cantidad = 2;</code>
     */
    public int getCantidad() {
      return cantidad_;
    }

    public static final int PRECIO_FIELD_NUMBER = 3;
    private double precio_;
    /**
     * <code>double precio = 3;</code>
     */
    public double getPrecio() {
      return precio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (cantidad_ != 0) {
        output.writeInt32(2, cantidad_);
      }
      if (precio_ != 0D) {
        output.writeDouble(3, precio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (cantidad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cantidad_);
      }
      if (precio_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, precio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.TramitadorOuterClass.ProductoRequest)) {
        return super.equals(obj);
      }
      grpc.TramitadorOuterClass.ProductoRequest other = (grpc.TramitadorOuterClass.ProductoRequest) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getCantidad()
          == other.getCantidad());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrecio())
          == java.lang.Double.doubleToLongBits(
              other.getPrecio()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CANTIDAD_FIELD_NUMBER;
      hash = (53 * hash) + getCantidad();
      hash = (37 * hash) + PRECIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrecio()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.ProductoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.TramitadorOuterClass.ProductoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductoRequest)
        grpc.TramitadorOuterClass.ProductoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.TramitadorOuterClass.internal_static_ProductoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.TramitadorOuterClass.internal_static_ProductoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.TramitadorOuterClass.ProductoRequest.class, grpc.TramitadorOuterClass.ProductoRequest.Builder.class);
      }

      // Construct using grpc.TramitadorOuterClass.ProductoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        cantidad_ = 0;

        precio_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.TramitadorOuterClass.internal_static_ProductoRequest_descriptor;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.ProductoRequest getDefaultInstanceForType() {
        return grpc.TramitadorOuterClass.ProductoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.ProductoRequest build() {
        grpc.TramitadorOuterClass.ProductoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.ProductoRequest buildPartial() {
        grpc.TramitadorOuterClass.ProductoRequest result = new grpc.TramitadorOuterClass.ProductoRequest(this);
        result.id_ = id_;
        result.cantidad_ = cantidad_;
        result.precio_ = precio_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.TramitadorOuterClass.ProductoRequest) {
          return mergeFrom((grpc.TramitadorOuterClass.ProductoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.TramitadorOuterClass.ProductoRequest other) {
        if (other == grpc.TramitadorOuterClass.ProductoRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getCantidad() != 0) {
          setCantidad(other.getCantidad());
        }
        if (other.getPrecio() != 0D) {
          setPrecio(other.getPrecio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.TramitadorOuterClass.ProductoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.TramitadorOuterClass.ProductoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int cantidad_ ;
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public int getCantidad() {
        return cantidad_;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder setCantidad(int value) {
        
        cantidad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder clearCantidad() {
        
        cantidad_ = 0;
        onChanged();
        return this;
      }

      private double precio_ ;
      /**
       * <code>double precio = 3;</code>
       */
      public double getPrecio() {
        return precio_;
      }
      /**
       * <code>double precio = 3;</code>
       */
      public Builder setPrecio(double value) {
        
        precio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double precio = 3;</code>
       */
      public Builder clearPrecio() {
        
        precio_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductoRequest)
    }

    // @@protoc_insertion_point(class_scope:ProductoRequest)
    private static final grpc.TramitadorOuterClass.ProductoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.TramitadorOuterClass.ProductoRequest();
    }

    public static grpc.TramitadorOuterClass.ProductoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductoRequest>
        PARSER = new com.google.protobuf.AbstractParser<ProductoRequest>() {
      @java.lang.Override
      public ProductoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.TramitadorOuterClass.ProductoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PedidoReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PedidoReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * resultado de la operación
     * </pre>
     *
     * <code>string resultado = 1;</code>
     */
    java.lang.String getResultado();
    /**
     * <pre>
     * resultado de la operación
     * </pre>
     *
     * <code>string resultado = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultadoBytes();
  }
  /**
   * Protobuf type {@code PedidoReply}
   */
  public  static final class PedidoReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PedidoReply)
      PedidoReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PedidoReply.newBuilder() to construct.
    private PedidoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PedidoReply() {
      resultado_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PedidoReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resultado_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.TramitadorOuterClass.internal_static_PedidoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.TramitadorOuterClass.internal_static_PedidoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.TramitadorOuterClass.PedidoReply.class, grpc.TramitadorOuterClass.PedidoReply.Builder.class);
    }

    public static final int RESULTADO_FIELD_NUMBER = 1;
    private volatile java.lang.Object resultado_;
    /**
     * <pre>
     * resultado de la operación
     * </pre>
     *
     * <code>string resultado = 1;</code>
     */
    public java.lang.String getResultado() {
      java.lang.Object ref = resultado_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultado_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * resultado de la operación
     * </pre>
     *
     * <code>string resultado = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultadoBytes() {
      java.lang.Object ref = resultado_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultado_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultadoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resultado_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultadoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resultado_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.TramitadorOuterClass.PedidoReply)) {
        return super.equals(obj);
      }
      grpc.TramitadorOuterClass.PedidoReply other = (grpc.TramitadorOuterClass.PedidoReply) obj;

      boolean result = true;
      result = result && getResultado()
          .equals(other.getResultado());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULTADO_FIELD_NUMBER;
      hash = (53 * hash) + getResultado().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.TramitadorOuterClass.PedidoReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.TramitadorOuterClass.PedidoReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PedidoReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PedidoReply)
        grpc.TramitadorOuterClass.PedidoReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.TramitadorOuterClass.internal_static_PedidoReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.TramitadorOuterClass.internal_static_PedidoReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.TramitadorOuterClass.PedidoReply.class, grpc.TramitadorOuterClass.PedidoReply.Builder.class);
      }

      // Construct using grpc.TramitadorOuterClass.PedidoReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resultado_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.TramitadorOuterClass.internal_static_PedidoReply_descriptor;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoReply getDefaultInstanceForType() {
        return grpc.TramitadorOuterClass.PedidoReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoReply build() {
        grpc.TramitadorOuterClass.PedidoReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.TramitadorOuterClass.PedidoReply buildPartial() {
        grpc.TramitadorOuterClass.PedidoReply result = new grpc.TramitadorOuterClass.PedidoReply(this);
        result.resultado_ = resultado_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.TramitadorOuterClass.PedidoReply) {
          return mergeFrom((grpc.TramitadorOuterClass.PedidoReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.TramitadorOuterClass.PedidoReply other) {
        if (other == grpc.TramitadorOuterClass.PedidoReply.getDefaultInstance()) return this;
        if (!other.getResultado().isEmpty()) {
          resultado_ = other.resultado_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.TramitadorOuterClass.PedidoReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.TramitadorOuterClass.PedidoReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resultado_ = "";
      /**
       * <pre>
       * resultado de la operación
       * </pre>
       *
       * <code>string resultado = 1;</code>
       */
      public java.lang.String getResultado() {
        java.lang.Object ref = resultado_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultado_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * resultado de la operación
       * </pre>
       *
       * <code>string resultado = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultadoBytes() {
        java.lang.Object ref = resultado_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultado_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * resultado de la operación
       * </pre>
       *
       * <code>string resultado = 1;</code>
       */
      public Builder setResultado(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultado_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * resultado de la operación
       * </pre>
       *
       * <code>string resultado = 1;</code>
       */
      public Builder clearResultado() {
        
        resultado_ = getDefaultInstance().getResultado();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * resultado de la operación
       * </pre>
       *
       * <code>string resultado = 1;</code>
       */
      public Builder setResultadoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultado_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PedidoReply)
    }

    // @@protoc_insertion_point(class_scope:PedidoReply)
    private static final grpc.TramitadorOuterClass.PedidoReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.TramitadorOuterClass.PedidoReply();
    }

    public static grpc.TramitadorOuterClass.PedidoReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PedidoReply>
        PARSER = new com.google.protobuf.AbstractParser<PedidoReply>() {
      @java.lang.Override
      public PedidoReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PedidoReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PedidoReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PedidoReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.TramitadorOuterClass.PedidoReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PedidoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PedidoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PedidoReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PedidoReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016sesion10.proto\"n\n\rPedidoRequest\022\020\n\010idP" +
      "edido\030\001 \001(\t\022\021\n\tdireccion\030\002 \001(\t\022\023\n\013restau" +
      "rante\030\003 \001(\005\022#\n\tproductos\030\004 \003(\0132\020.Product" +
      "oRequest\"?\n\017ProductoRequest\022\n\n\002id\030\001 \001(\t\022" +
      "\020\n\010cantidad\030\002 \001(\005\022\016\n\006precio\030\003 \001(\001\" \n\013Ped" +
      "idoReply\022\021\n\tresultado\030\001 \001(\t28\n\nTramitado" +
      "r\022*\n\010tramitar\022\016.PedidoRequest\032\014.PedidoRe" +
      "ply\"\000B\034\n\004grpcB\024TramitadorOuterClassb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PedidoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PedidoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PedidoRequest_descriptor,
        new java.lang.String[] { "IdPedido", "Direccion", "Restaurante", "Productos", });
    internal_static_ProductoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductoRequest_descriptor,
        new java.lang.String[] { "Id", "Cantidad", "Precio", });
    internal_static_PedidoReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PedidoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PedidoReply_descriptor,
        new java.lang.String[] { "Resultado", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
